---
abstract: 'A Plack middleware adding Content Security Policy information'
author:
  - 'Leon Timmermans'
build_requires:
  HTTP::Request::Common: '0'
  Plack::Builder: '0'
  Plack::Test: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.039'
  perl: '5.006'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.008, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-CSP
provides:
  Plack::Middleware::CSP:
    file: lib/Plack/Middleware/CSP.pm
    version: '0.001'
requires:
  List::Util: '1.33'
  MIME::Base64: '0'
  Plack::Middleware: '0'
  Plack::Util: '0'
  Plack::Util::Accessor: '0'
  parent: '0'
version: '0.001'
